version: '3'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: API\Dockerfile

  identity.api:
    image: identity.api
    build:
      context: .
      dockerfile: ..\Identity.API\Dockerfile

