version: '3'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  hkexnews.background:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

