version: '3'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: src/API/Dockerfile

  hkexnews.background:
    image: hkexnews.background
    build:
      context: .
      dockerfile: src/HKExNews.Background/Dockerfile

